// src/components/StartupReport/actions/ShareButton.jsx
import { Share2 } from "lucide-react";
import ActionButton from "./ActionButton";
import { useState } from "react";

export default function ShareButton() {
  const [copied, setCopied] = useState(false);

  const handleShare = async () => {
    try {
      const shareUrl = window.location.href;

      if (navigator.share) {
        // ✅ Use native share if available (mobile)
        await navigator.share({
          title: "Ideafy Startup Report",
          text: "Check out this startup report generated by Ideafy.",
          url: shareUrl,
        });
      } else {
        // ✅ Fallback: copy to clipboard
        await navigator.clipboard.writeText(shareUrl);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }
    } catch (error) {
      console.error("❌ Failed to share link:", error);
      alert("Could not generate share link. Please try again.");
    }
  };

  return (
    <ActionButton
      onClick={handleShare}
      icon={Share2}
       label={copied ? "Link Copied!" : "Share"}
        gradient="bg-gradient-to-r from-blue-500 to-cyan-500"
      variant="outline"   
    />
  );
}

 